### PR TITLE
Support react-native 0.29

### LINKED ISSUE #83: RN 0.29 installation guide change
https://github.com/facebook/react-native/releases/tag/v0.29.0-rc.0

### PR DESCRIPTION
**Pull request by youennPennarun**
Since [RN 0.29](https://github.com/facebook/react-native/releases/tag/v0.29.0), getPackages() is defined in MainApplication, so modules's constructors can't have access to the activity. It's now required to call `getCurrentActivity()` from ReactContextBaseJavaModule whenever the activity is needed.

As the activity is attached to the context in `onResume`, OrientationModule also need to implement LifecycleEventListener to be able to call `activity.registerReceiver`

This pull request would close #83

### CODE REVIEW

**Comment by jwarby** [comment]
I just tried your fork @youennPennarun and it wasn't working for me until I added the following to `OrientationModule`'s constructor:
```java
ctx.addLifecycleEventListener(this);
```

Looks to be working perfectly on RN0.29 with that addition though, thanks!

**Comment by youennPennarun** [comment]
Indeed, I forgot to add this line. Thanks @jwarby

**Comment by philipheinser** [comment]
@yamill Can you merge this one?

File: android/src/main/java/com/github/yamill/orientation/OrientationModule.java [hunk 1]
```diff
@@ -105,26 +74,36 @@ public void getOrientation(Callback callback) {
 
     @ReactMethod
     public void lockToPortrait() {
+        final Activity mActivity = getCurrentActivity();
+        if (mActivity == null) return;
```
Comment (philikon) [inline android/src/main/java/com/github/yamill/orientation/OrientationModule.java]: coding style nits: indentation is off, `if` should be followed by a block, rename `mActivity` to `activity` since it's no longer a member anymore.

**Comment by youennPennarun** [comment]
Should be OK.

**Comment by SudoPlz** [comment]
Thanks for that @youennPennarun and the rest of you guys!

**Comment by winterbe** [comment]
Thanks for this. Any ETA when it will be merged and released?

**Comment by donedgardo** [comment]
I'm not sure how to implement this change i changed the package.json to point to "youennPennarun/react-native-orientation#master", removed node_modules and `npm i`.
Afterwards i ran ` rnpm link react-native-orientation`
After linking i run `react-native run-android`
I followed the configuration steps for the android files
Runing into these errors
```
/Main
Activity.java:46: error: method does not override or implement a method from a superty
pe
    @Override
    ^
/Users/donedgardo/skyrocket/piso13RNApp/android/app/src/main/java/com/piso13rnapp/Main
Activity.java:51: error: constructor OrientationPackage in class OrientationPackage ca
nnot be applied to given types;
            new OrientationPackage(this),
            ^
  required: no arguments
  found: MainActivity
  reason: actual and formal argument lists differ in length
2 errors
```

Not sure if im doing this right, or that theres an issue with my configuration.

**Comment by Dudyboy** [comment]
Could you please help me to implement this package, because it is not work for me. When I used RN 0.26, it works fine, but now with RN 0.29, they add MainApplication.java and I am confused.

I fork this pull request with support for RN 0.29 and run rnpm:

```javascript
sudo rnpm link react-native-orientation 
```

Everything works fine, console log

```javascript
rnpm-link info Linking react-native-orientation android dependency 
rnpm-link info Android module react-native-orientation has been successfully linked 
rnpm-link info Linking react-native-orientation ios dependency 
rnpm-link info iOS module react-native-orientation has been successfully linked 
```

I do not know, if I have to add 3. step in installation (Register module (in MainActivity.java)) and where do I have to add configuration?

Thank you very much for answers.

**Comment by youennPennarun** [comment]
@Dudyboy Did you upgraded your application to RN0.29.2? Since modules aren't instantiated in MainActivity anymore, rnpm was broken with RN0.29.0. This has been fixed in [RN0.29.2](https://github.com/facebook/react-native/releases/tag/v0.29.2).
After the upgrade, try `react-native link`

**Comment by Dudyboy** [comment]
Thank you for answer. Yes, I have RN0.29.2.

Dependencies:
```javascript
    "react": "15.2.1",
    "react-native": "0.29.2",
    "react-native-orientation": "git+https://github.com/Dudyboy/react-native-orientation.git",
```

MainActivity looks like this:

```javascript
package com.newapp;

import com.facebook.react.ReactActivity;
import com.github.yamill.orientation.OrientationPackage;
import android.content.Intent;
import android.content.res.Configuration;

public class MainActivity extends ReactActivity {

    @Override
      public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        Intent intent = new Intent("onConfigurationChanged");
        intent.putExtra("newConfig", newConfig);
        this.sendBroadcast(intent);
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "newApp";
    }
}
```

MainApplication.java looks like:

```javascript
package com.newapp;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.github.yamill.orientation.OrientationPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new OrientationPackage(this)
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

It shows error 

```javascript
incompatible types: <anonymous ReactNativeHost> cannot be converted to Activity
          new OrientationPackage(this)
                                 ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

What am I doing wrong?

**Comment by youennPennarun** [comment]
Your fork doesn't contain this pull request, as you can see when you [compare my fork with yours](https://github.com/yamill/react-native-orientation/compare/master...youennPennarun:master).

**Comment by Dudyboy** [comment]
You are rgiht :) ... my mistake. Now is everthing working like charm.

Thank you very much.

**Comment by srhise** [comment]
@yamill Any update on when this will be released?

**Comment by donedgardo** [comment]
I'm getting these errors:
```
Application.java:44: error: constructor OrientationPackage in class OrientationPackage
 cannot be applied to given types;
              new OrientationPackage(this)
              ^
  required: no arguments
  found: <anonymous ReactNativeHost>
  reason: actual and formal argument lists differ in length
1 error
```

Also its notifying me inside MainApplication.java 

import com.github.yamill.orientation. **OrientationPackage**;
'Cannot resolve symbol OrientationPackage'.

Pls help.

**Comment by youennPennarun** [comment]
@donedgardo It's `new OrientationPackage()`, there is no arguments anymore.
I updated the readme to reflect that change.

**Comment by ronaldheft** [comment]
@youennPennarun I pulled down your fork. It fixes my Android build issues, but the orientation listeners are not working. I can lock / unlock orientation without issues, and my views rotate when unlocked, so I know orientation events are making it into the application. Just the listeners are not firing (listeners work fine on iOS).

**Comment by zaynyatyi** [comment]
Works fine for me

**Comment by ronaldheft** [comment]
@zaynyatyi I figured out the issue is there is no Android support for the rotation specific listeners. The regular orientation listeners work fine.

I put this on the backburner for my app for the moment, but I eventually plan to circle back and add Android support for rotation specific listeners if no one beats me to it.

**Comment by igrayson** [comment]
@youennPennarun you might consider leaving the Activity constructor, so upgraders have less friction.

@ronaldheft to clarify, you had no issue with this PR that you wouldn't have with master, correct?

I'd like to get this merged up. I have some additional changes staged that build on this.

**Comment by ronaldheft** [comment]
@igrayson Correct, this PR is working.

**Comment by yamill** [comment]
Hi guys, just merged this! Thanks so much for supporting this. I haven't had time lately, would be awesome if anyone wants to help take over this module!
